### ISSUE TITLE
Difficult navigation on mobile due to menu issues 

### ISSUE THREAD

**Issue by QORTEC** [serpent-os/serpentos.com#4]
As can be seen from the provided screenshot, the site menu has no/transparent background, which makes navigation difficult.

![SerpentOS.com/Dark-Mode](https://user-images.githubusercontent.com/4239654/205145020-2517e562-0e98-4f2f-b10f-ea871be9b172.jpg)

As can be seen from the second screenshot this effects both `Light` and `Dark`. 

However on the `Light` theme the `menu` and `close` buttons are not visible, likely due to said buttons being white on a white background. 

![SerpentOS.com/Light-Mode](https://user-images.githubusercontent.com/4239654/205145004-e41c5a49-0211-4746-bc7c-558fe1f580f7.jpg)

Schreenshots from Firefox on Android 11, using Samsung Tab S5e.

**Comment by linuxer0x42** [comment]
Same problem for me, the websites menu is invisible on mobile (in light mode) but still can be clicked, once clicked it doesn't have any background and it makes it harder to see other stuff of the website (in both light & dark mode).

**Comment by Staudey** [comment]
Should be fixed by https://github.com/serpent-os/serpentos.com/pull/6

**Comment by QORTEC** [comment]
Thanks, can confirm that the issue has been resolved.
